services:
  init:
    image: alpine:latest
    container_name: statementai-init
    volumes:
      - ./backend/setup.sh:/setup.sh
      - ./.env:/.env
      - ${DATA_PATH}:${DATA_PATH}
    entrypoint: sh /setup.sh
    env_file:
      - .env
    user: "0"
    networks:
      - default

  frontend:
    build: ./frontend
    container_name: statementai-frontend
    ports:
      - "3000:3000"
    env_file:
      - .env

  backend:
    build: ./backend
    container_name: statementai-backend-api
    ports:
      - "8765:8765"
    volumes:
      - ${DATA_PATH}/uploads:/app/uploads
    depends_on:
      elasticsearch:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    env_file:
      - .env

  elasticsearch:
    container_name: statementai-es
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.http.ssl.enabled=false
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD} 
    ports:
      - "9200:9200"
    volumes:
      - ${DATA_PATH}/esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s -u elastic:${ELASTIC_PASSWORD} http://localhost:9200/_cluster/health | grep -q 'status'"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 40s

  mongodb:
    container_name: statementai-mongo
    image: mongo:8.0
    ports:
      - "27017:27017"
    command: ["mongod", "--auth"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ${DATA_PATH}/mongodata:/data/db
      - ./backend/init-mongodb.sh:/docker-entrypoint-initdb.d/init-mongodb.sh
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "try { db.adminCommand('ping') } catch(e) { exit(1) }"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 30s

volumes:
  esdata:
  mongodata: